### ISSUE TITLE
Changing theme colours

### ISSUE THREAD

**Issue by jrosen48** [jbub/ghostwriter#31]
Thanks for a great theme. I am new to Hugo and am trying to change the default font. I first considered the settings in the "Colours" section of `style.scss`, but changing these did not seem to change the appearance. Can you recommend how I can make changes to them?

Josh

**Comment by jbub** [comment]
Hey, in order to change the styles you would have to install the javascript dependencies for generating SCSS to CSS. There is a short text about it in the README (https://github.com/jbub/ghostwriter#development). If you are not familiar with the JS ecosystem, you can walk trough the `yarn` steps here https://yarnpkg.com/lang/en/docs/getting-started/. Please feel free to ask any questions, i will try my best to help. Thank you
